### ISSUE TITLE
Docker-Images: prysm

### ISSUE THREAD

**Issue by stefa2k** [stefa2k/ethereum2-docker-compose#19]
Build a secure docker image for prysm:
- beacon-chain
- validator
- slasher

Docker image features:
- Using non-priviledged user
- Apparmor or similar
- No package managers
- Automized and triggered builds

**Comment by sapien99** [comment]
Thinking of either to use alpine or minideb. In both cases we will use a buildpipeline with multistage docker builds for building the image, remove the package-manager and then use Apparmor to check and harden the image

**Comment by stefa2k** [comment]
Continue here: https://github.com/stereum-dev/ethereum2-docker-build/issues/1
